# Generated by Django 5.2.6 on 2025-11-10 20:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('CAJERO', 'Cajero'), ('DELIVERY', 'Repartidor')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo actual en la billetera', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Si la billetera está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario dueño de la billetera', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Reembolso de devolución'), ('PURCHASE', 'Compra con billetera'), ('WITHDRAWAL', 'Retiro de fondos'), ('DEPOSIT', 'Depósito manual'), ('BONUS', 'Bono o promoción'), ('CORRECTION', 'Corrección de saldo')], help_text='Tipo de transacción', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto (positivo=crédito, negativo=débito)', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Saldo después de la transacción', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('REVERSED', 'Revertida')], default='COMPLETED', help_text='Estado de la transacción', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción de la transacción')),
                ('reference_id', models.CharField(blank=True, help_text='ID de referencia (ej: Return ID, Order ID)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(help_text='Billetera asociada', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet')),
            ],
            options={
                'verbose_name': 'Transacción de Billetera',
                'verbose_name_plural': 'Transacciones de Billetera',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_walle_created_8cdd16_idx'), models.Index(fields=['wallet', '-created_at'], name='users_walle_wallet__7a1893_idx'), models.Index(fields=['transaction_type'], name='users_walle_transac_478769_idx'), models.Index(fields=['reference_id'], name='users_walle_referen_4b2234_idx')],
            },
        ),
    ]
