# Generated by Django 5.2.6 on 2025-11-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role_wallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token FCM del dispositivo', max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', help_text='Tipo de dispositivo', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='ID único del dispositivo (opcional)', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Nombre del dispositivo (ej: "iPhone 15 Pro de Juan")', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo (se desactiva si el token es inválido)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del token')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Última vez que se usó este token')),
                ('user', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(help_text='Tipo de notificación: ORDER_DELIVERED, RETURN_APPROVED, etc.', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales enviados con la notificación')),
                ('status', models.CharField(choices=[('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('DELIVERED', 'Entregada')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la notificación falló', null=True)),
                ('fcm_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de FCM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='users.devicetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='users_devic_user_id_92ecdc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='users_devic_token_271e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'notification_type'], name='users_notif_user_id_087c45_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='users_notif_created_589474_idx'),
        ),
    ]
