# Generated by Django 5.2.6 on 2025-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
