# Generated by Django 5.2.6 on 2025-11-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_return_completed_at_return_evaluated_at_and_more'),
        ('shop_orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(help_text='ID del payment intent de Stripe', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='ID del charge de Stripe', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto total pagado', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Moneda del pago', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado'), ('PARTIALLY_REFUNDED', 'Parcialmente reembolsado')], default='PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method_type', models.CharField(blank=True, help_text='Tipo de método de pago (card, etc.)', max_length=50, null=True)),
                ('last4', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop_orders.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(help_text='ID del refund de Stripe', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto reembolsado', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SUCCEEDED', 'Exitoso'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(help_text='Usuario que inició el reembolso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='shop_orders.payment')),
                ('return_obj', models.ForeignKey(blank=True, help_text='Devolución asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_refunds', to='deliveries.return')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
    ]
