# Generated by Django 5.2.6 on 2025-10-26 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FAILED', 'Intento de Login Fallido'), ('USER_CREATE', 'Creación de Usuario'), ('USER_UPDATE', 'Actualización de Usuario'), ('USER_DELETE', 'Eliminación de Usuario'), ('PRODUCT_CREATE', 'Creación de Producto'), ('PRODUCT_UPDATE', 'Actualización de Producto'), ('PRODUCT_DELETE', 'Eliminación de Producto'), ('PRODUCT_VIEW', 'Visualización de Producto'), ('ORDER_CREATE', 'Creación de Orden'), ('ORDER_UPDATE', 'Actualización de Orden'), ('ORDER_DELETE', 'Eliminación de Orden'), ('ORDER_PAYMENT', 'Pago de Orden'), ('ORDER_CANCEL', 'Cancelación de Orden'), ('REPORT_GENERATE', 'Generación de Reporte'), ('REPORT_DOWNLOAD', 'Descarga de Reporte'), ('NLP_QUERY', 'Consulta NLP'), ('SYSTEM_ERROR', 'Error del Sistema'), ('PERMISSION_DENIED', 'Acceso Denegado'), ('DATA_EXPORT', 'Exportación de Datos')], max_length=50, verbose_name='Acción')),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Severidad')),
                ('username', models.CharField(blank=True, help_text='Guardado en caso de que el usuario sea eliminado', max_length=150, verbose_name='Nombre de Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Ruta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('object_type', models.CharField(blank=True, help_text='Ej: Product, Order, User', max_length=100, verbose_name='Tipo de Objeto')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Representación del Objeto')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Datos Adicionales')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_a_timesta_e00a3a_idx'), models.Index(fields=['user'], name='audit_log_a_user_id_803677_idx'), models.Index(fields=['action'], name='audit_log_a_action_903622_idx'), models.Index(fields=['ip_address'], name='audit_log_a_ip_addr_867599_idx'), models.Index(fields=['severity'], name='audit_log_a_severit_f5f35f_idx')],
            },
        ),
    ]
