# Generated by Django 5.2.6 on 2025-11-10 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_rename_address_delivery_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de completado', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de evaluación', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='evaluation_notes',
            field=models.TextField(blank=True, help_text='Notas de la evaluación física realizada por tercero'),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_method',
            field=models.CharField(choices=[('WALLET', 'Billetera virtual'), ('ORIGINAL', 'Método de pago original'), ('BANK', 'Transferencia bancaria')], default='WALLET', help_text='Método de reembolso', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Cliente que solicita la devolución', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='description',
            field=models.TextField(help_text='Descripción del cliente del problema'),
        ),
        migrations.AlterField(
            model_name='return',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Notas del manager sobre la decisión'),
        ),
        migrations.AlterField(
            model_name='return',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de procesamiento del reembolso', null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto a reembolsar (calculado automáticamente)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Solicitada por cliente'), ('IN_EVALUATION', 'En evaluación física'), ('APPROVED', 'Aprobada - Procesando reembolso'), ('REJECTED', 'Rechazada'), ('COMPLETED', 'Completada - Reembolso realizado')], default='REQUESTED', max_length=20),
        ),
    ]
